/**
 * @author Raj Dye - raj@rajdye.com
 * Copyright (c) 2011 Institute for Sustainable Performance of Buildings (Superb)
 */
 
goog.provide('lgb.model.PsModel');

goog.require('lgb.events.DataModelChanged');
goog.require('lgb.model.BaseModel');
goog.require('lgb.utils.XmlParser');


/**
 * @constructor
 * @extends lgb.model.BaseModel
 * @param {Object} systemConfig The particle system config
 * generated by parsing the XML.
 */
lgb.model.PsModel = function(systemConfig, idx) {

  /**
   * @const
   * @type {string}
   */
  this._NAME = 'lgb.model.PsModel';
  this.idx = idx;

  /**@type {string} */
  this.title = systemConfig.title;

  lgb.model.BaseModel.call(this);

  this.isRunning = false;
  this.isStarted = false;
  this.showBoxes = false;
  this.showCurves = false;
  this.isEmitting = true;
  this.particleCount = systemConfig.particleCount;
  this.particleSize = systemConfig.particleSize;
  this.meshes = systemConfig.meshes;
  this.rotate = systemConfig.rotate;
  this.translate = systemConfig.translate;
  this.id = systemConfig.id;
  this.launchDelayBetweenParticles = systemConfig.launchDelayBetweenParticles;
  this.lifeSpanInSeconds = systemConfig.lifeSpanInSeconds;
};
goog.inherits(lgb.model.PsModel, lgb.model.BaseModel);





lgb.model.PsModel.prototype.changeProperty_isStarted = function( newValue) {
  
    var whatIsDirty = {};
    
    this.isStarted = newValue;
    
    if (this.isStarted) {
      if (!this.isRunning) {
        this.isRunning = true;
        whatIsDirty.isRunning = true;
      }
      if (!this.isEmitting) {
        this.isEmitting = true;
        whatIsDirty.isEmitting = true;
      }
    } else {
      if (this.isEmitting) {
        this.isEmitting = false;
        whatIsDirty.isEmitting = true;
      }
    }
    
    this.dispatchChange(whatIsDirty);
}


lgb.model.PsModel.prototype.changeProperty = function(propertyName, propertyValue) {

    if (this[propertyName] != propertyValue) {
      if (propertyName == 'isStarted') {
        
        this.changeProperty_isStarted(propertyValue);
        
      } else {
        
       goog.base(this, 'changeProperty', propertyName, propertyValue);
       
      }
    }
}



